constants:
  file:
    directory: /home/download

server:
  port: 8080

spring:
  application:
    name: user-service
  config:
    import:
      - optional:classpath:application-common-prod.yaml
      - optional:classpath:application-auth-prod.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${USER_DB_HOST}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
